{
    "openapi": "3.0.0",
    "info": {
        "title": "API Swagger documentation",
        "version": "1.0"
    },
    "paths": {
        "/api/login": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "operationId": "d846bd02cfbdd992c40bfde736b5f21d",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "password"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Adds a new user",
                "operationId": "887d97246c6c4a812a1867fa2f50e90e",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "confirm_password"
                                ],
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "confirm_password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/control/{uid}/add": {
            "post": {
                "tags": [
                    "Control"
                ],
                "summary": "Adds a new control",
                "operationId": "9720ded00bf23eaa0cc8f26580e7e082",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "Add control for uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 3
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "domains": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "example": [
                                            "google.com",
                                            "yandex.ru",
                                            "site1.net"
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Control_domain"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/control/{cid}": {
            "get": {
                "tags": [
                    "Control"
                ],
                "summary": "Get control by cid",
                "operationId": "b7ffcf595c9add4245ac0ec6f332ab51",
                "parameters": [
                    {
                        "name": "cid",
                        "in": "path",
                        "description": "Control to fetch",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 4
                    }
                ],
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Control_domain"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Control"
                ],
                "summary": "Updates a control",
                "operationId": "c00d506424568eca975c5d425d3729b7",
                "parameters": [
                    {
                        "name": "cid",
                        "in": "path",
                        "description": "cid to update",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "control": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "control": "google.com"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/control/{uid}/{cid}": {
            "get": {
                "tags": [
                    "Control"
                ],
                "summary": "Get control by uid",
                "operationId": "8ec1f5d3c2082682356edfd3b04f6610",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "Control fetch by uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 3
                    },
                    {
                        "name": "cid",
                        "in": "path",
                        "description": "Control fetch by cid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 0
                    },
                    {
                        "name": "did",
                        "in": "query",
                        "description": "did",
                        "schema": {
                            "type": "string"
                        },
                        "example": 2
                    },
                    {
                        "name": "domain",
                        "in": "query",
                        "description": "domain",
                        "schema": {
                            "type": "string"
                        },
                        "example": "site.com"
                    },
                    {
                        "name": "select",
                        "in": "query",
                        "description": "select",
                        "schema": {
                            "type": "string"
                        },
                        "example": "host_id,hidden,pos_settings"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Control_domain"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Control"
                ],
                "description": "deletes a single control ",
                "operationId": "4bc11c103dbe9fcb759d00030bcbcfc5",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 3
                    },
                    {
                        "name": "cid",
                        "in": "path",
                        "description": "cid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 0
                    }
                ],
                "responses": {
                    "204": {
                        "description": "control deleted"
                    },
                    "default": {
                        "description": "unexpected error"
                    }
                }
            }
        },
        "/api/control/{uid}/{cid}/set_lr/{lr}": {
            "get": {
                "tags": [
                    "Control"
                ],
                "summary": "Set control lr by uid, cid",
                "operationId": "4e6458972547f9ddec10109400b6e1d1",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 4
                    },
                    {
                        "name": "cid",
                        "in": "path",
                        "description": "cid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 4
                    },
                    {
                        "name": "lr",
                        "in": "path",
                        "description": "lr",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 1
                    }
                ],
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Control_domain"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/control/{uid}/groups/": {
            "get": {
                "tags": [
                    "Control"
                ],
                "summary": "Get groups  list",
                "operationId": "cbcca4999a6199863a27d185dce705f7",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "Groups fetch by uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        },
                        "example": 3
                    },
                    {
                        "name": "gid",
                        "in": "query",
                        "description": "gid",
                        "schema": {
                            "type": "string"
                        },
                        "example": "1,3"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "control response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Control_domain"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/domains/add": {
            "post": {
                "tags": [
                    "Domains"
                ],
                "summary": "Adds a new domains from array",
                "operationId": "c057464b069c41cc29b854a1d143be1b",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "check_exist": {
                                        "type": "boolean",
                                        "example": false
                                    },
                                    "domains": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "example": [
                                            "google.com",
                                            "yandex.ru",
                                            "site1.net"
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Domain"
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "data": {
                                        "0": {
                                            "domain": "google.com",
                                            "did": 13,
                                            "status": 200
                                        },
                                        "status_arr": {
                                            "200": "Dpmain created",
                                            "501": "Domain not registered error",
                                            "502": "Domain too short error",
                                            "503": "Domain too long error",
                                            "504": "Domain should start from letter",
                                            "505": "Wrong domain error",
                                            "506": "Domain Incorect symbols error",
                                            "508": "Domain already exist",
                                            "509": "Domain control already exist"
                                        }
                                    },
                                    "message": "Request processed"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/domains/{did}": {
            "get": {
                "tags": [
                    "Domains"
                ],
                "summary": "Get domain by did",
                "operationId": "a7f58ffa3de54611f08c707f927796b3",
                "parameters": [
                    {
                        "name": "did",
                        "in": "path",
                        "description": "did to fetch",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "domain response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Domain"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/domains/check": {
            "post": {
                "tags": [
                    "Domains"
                ],
                "summary": "Check domains from array",
                "operationId": "5e1236c0ec8d0b9c49095a5fc201eefe",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "check_exist": {
                                        "type": "boolean",
                                        "example": false
                                    },
                                    "domains": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "example": [
                                            "google.com",
                                            "yandex.ru",
                                            "site1.net"
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "domain response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Domain"
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "data": [
                                        {
                                            "domain": "google.com",
                                            "status": 200
                                        }
                                    ],
                                    "message": "Request processed"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/domains/get_did": {
            "post": {
                "tags": [
                    "Domains"
                ],
                "summary": "Adds a new domains from array",
                "operationId": "5b087d2e43ab11897627d40db5e23014",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "domains": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "example": [
                                            "google.com",
                                            "yandex.ru",
                                            "site1.net"
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "domain response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Domain"
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "data": [
                                        {
                                            "domain": "ya.ru",
                                            "did": 19
                                        },
                                        {
                                            "domain": "11111",
                                            "did": false
                                        }
                                    ],
                                    "message": "Request processed"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/domains/get_domain": {
            "post": {
                "tags": [
                    "Domains"
                ],
                "summary": "Get domain domains by did array",
                "operationId": "2e91d5de6144ac3c5b9e1c1a47859232",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "did": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "": {
                                                    "type": "integer"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "example": [
                                            11,
                                            12,
                                            13
                                        ]
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "domain response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Domain"
                                    }
                                },
                                "example": {
                                    "success": true,
                                    "data": [
                                        {
                                            "domain": "ya.ru",
                                            "did": 19
                                        },
                                        {
                                            "domain": false,
                                            "did": 12
                                        }
                                    ],
                                    "message": "Request processed"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/languages": {
            "get": {
                "tags": [
                    "Languages"
                ],
                "summary": "Get languages list",
                "operationId": "13f72dfeebea6adfa84684cf31bade15",
                "responses": {
                    "200": {
                        "description": "language response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Language"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/languages/{lang}": {
            "get": {
                "tags": [
                    "Languages"
                ],
                "summary": "Get language by lang",
                "operationId": "102bf94e2acc5ac55f646cec845c9101",
                "parameters": [
                    {
                        "name": "lang",
                        "in": "path",
                        "description": "laтg to fetch",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "language response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Language"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/lrs": {
            "get": {
                "tags": [
                    "Lr"
                ],
                "summary": "Get lrs list",
                "operationId": "9bc225375276dc1ad2771727be9ce9a8",
                "responses": {
                    "200": {
                        "description": "lr response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Location"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/lrs/{lr}": {
            "get": {
                "tags": [
                    "Lr"
                ],
                "summary": "Get location by lr",
                "operationId": "71be1c166f1fca4cbaee03d9a44df6cc",
                "parameters": [
                    {
                        "name": "lr",
                        "in": "path",
                        "description": "lr to fetch",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "lr response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Location"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/lrs/search/{search}": {
            "get": {
                "tags": [
                    "Lr"
                ],
                "summary": "Get lr search",
                "operationId": "b7e93af3595058a287e9586af188ce3a",
                "parameters": [
                    {
                        "name": "search",
                        "in": "path",
                        "description": "search",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "Мос"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "lr response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Location"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/user-settings/{uid}": {
            "get": {
                "tags": [
                    "User Settings"
                ],
                "summary": "Get settings list for uid",
                "operationId": "c649b5e4daf1f565d281532a23cc60b0",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 3
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Settings response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Settings"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "User Settings"
                ],
                "summary": "Adds a new Settings",
                "operationId": "659174abf6e543b55dc6594832568733",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "value"
                                ],
                                "properties": {
                                    "uid": {
                                        "type": "integer"
                                    },
                                    "type": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "lr response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Settings"
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/user-settings/{uid}/{sid}": {
            "get": {
                "tags": [
                    "User Settings"
                ],
                "summary": "Get Settings by {sid}",
                "operationId": "455dfc9e523170d0df5c706ba6053ddc",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 3
                        }
                    },
                    {
                        "name": "sid",
                        "in": "path",
                        "description": "cid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 3
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "lr response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Settings"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "User Settings"
                ],
                "description": "deletes a single setting by sid",
                "operationId": "eb7830af24317644af7ac58c400f99d4",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "sid",
                        "in": "path",
                        "description": "sid to delete",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "setting deleted"
                    },
                    "default": {
                        "description": "unexpected error"
                    }
                }
            }
        },
        "/api/user-settings/{uid}/search": {
            "get": {
                "tags": [
                    "User Settings"
                ],
                "summary": "Get Settings for user {uid} and optional {type}",
                "operationId": "5de9041501e7ea8fd374e1972130e21e",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "example": 3
                        }
                    },
                    {
                        "name": "type",
                        "in": "query",
                        "description": "type",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "example": "show"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "lr response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Settings"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "sanctum": []
                    }
                ]
            }
        },
        "/api/user-settings/{uid}/update": {
            "post": {
                "tags": [
                    "User Settings"
                ],
                "summary": "Updates settings for uid and type",
                "operationId": "5c834cc6a080e80b8ad51a8b367c49e5",
                "parameters": [
                    {
                        "name": "uid",
                        "in": "path",
                        "description": "uid",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    },
                    {
                        "name": "type",
                        "in": "query",
                        "description": "type",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "example": "show"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "value"
                                ],
                                "properties": {
                                    "value": {
                                        "type": "array",
                                        "items": {
                                            "properties": {
                                                "": {
                                                    "type": "string"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "example": {
                                            "column_pos": 0
                                        }
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Result": {
                "title": "Responce",
                "properties": {
                    "success": {
                        "type": "string"
                    },
                    "data": {
                        "type": "object"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "200": "Dpmain created",
                    "501": "Domain not registered error",
                    "502": "Domain too short error",
                    "503": "Domain too long error",
                    "504": "Domain should start from letter",
                    "505": "Wrong domain error",
                    "506": "Domain Incorect symbols error",
                    "508": "Domain already exist",
                    "509": "Domain control already exist"
                }
            },
            "Control_domain": {
                "type": "object",
                "allOf": [
                    {
                        "required": [
                            "did"
                        ],
                        "properties": {
                            "cid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "uid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "did": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "yid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "metrika_id": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "yandex_id": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "host_id": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "lr": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "gid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "pos_settings": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    }
                ]
            },
            "Groups": {
                "type": "object",
                "allOf": [
                    {
                        "required": [
                            "uid"
                        ],
                        "properties": {
                            "gid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "uid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "group_name": {
                                "type": "string"
                            },
                            "value": {
                                "type": "array",
                                "items": {
                                    "properties": {
                                        "": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "skip_already": 0,
                                        "use_yandex_xml": 0,
                                        "select_gid": 0,
                                        "f_use_base": 1,
                                        "f_skip_already": 1,
                                        "f_check_old": 1
                                    }
                                }
                            }
                        },
                        "type": "object"
                    }
                ]
            },
            "Settings": {
                "type": "object",
                "allOf": [
                    {
                        "required": [
                            "uid"
                        ],
                        "properties": {
                            "sid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "uid": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "type": {
                                "type": "string"
                            },
                            "value": {
                                "type": "array",
                                "items": {
                                    "properties": {
                                        "": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object",
                                    "example": {
                                        "skip_already": 0,
                                        "use_yandex_xml": 0,
                                        "select_gid": 0,
                                        "f_use_base": 1,
                                        "f_skip_already": 1,
                                        "f_check_old": 1
                                    }
                                }
                            }
                        },
                        "type": "object"
                    }
                ]
            },
            "Domain": {
                "type": "object",
                "allOf": [
                    {
                        "$ref": "#/components/schemas/Domain"
                    },
                    {
                        "required": [
                            "domain"
                        ],
                        "properties": {
                            "did": {
                                "type": "integer",
                                "format": "int64"
                            },
                            "domain": {
                                "type": "string"
                            }
                        },
                        "type": "object",
                        "example": {
                            "did": 10,
                            "domain": "google.com"
                        }
                    }
                ]
            },
            "Language": {
                "type": "object",
                "allOf": [
                    {
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "lang": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "aparser": {
                                "type": "string"
                            },
                            "three": {
                                "type": "string"
                            },
                            "rucaptcha": {
                                "type": "integer"
                            }
                        },
                        "type": "object"
                    }
                ]
            },
            "Location": {
                "type": "object",
                "allOf": [
                    {
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "lr": {
                                "type": "integer"
                            },
                            "name": {
                                "type": "string"
                            },
                            "parent_id": {
                                "type": "string"
                            },
                            "parent_string": {
                                "type": "string"
                            },
                            "sort": {
                                "type": "integer"
                            },
                            "pop": {
                                "type": "integer"
                            }
                        },
                        "type": "object"
                    }
                ]
            },
            "User": {
                "type": "object",
                "allOf": [
                    {
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "email": {
                                "type": "string"
                            },
                            "password": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    }
                ]
            }
        },
        "securitySchemes": {
            "sanctum": {
                "type": "apiKey",
                "description": "Enter token in format (Bearer {token})",
                "name": "Authorization",
                "in": "header"
            }
        }
    },
    "security": [
        {
            "sanctum": []
        }
    ]
}